# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4b125c43e7703a9ddc39f093e77c1a896537510db23554d80f2bf63aadb9e8d237d1a3872a7015a41539a99cbe7f253ea28fae74390188f77eb6c4da9f3b09e

test:
  secret_key_base: 01a338f493ab76d22c49c72dd1c64e88176c46e80aeeb7f62ab48c8fa6ec9d0f2d8cec8d754f6feb46f7d7accf559117c09d9328394317078d7c033e9e3cba08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
